* Dklab Realplexor 2014-01-14: v1.41   - [MIN] Brushed up C++ version, Ubuntu 12.04 build instructions.   - [MIN] Banner comments added to source files.   - [MIN] Tabs to spaces.

diff --git a/dklab_realplexor.init b/dklab_realplexor.init
--- a/dklab_realplexor.init
+++ b/dklab_realplexor.init
@@ -9,8 +9,8 @@
 #
 ### BEGIN INIT INFO
 # Provides:          dklab_realplexor
-# Required-Start:    
-# Required-Stop:     
+# Required-Start:
+# Required-Stop:
 # Default-Start:     2 3 4 5
 # Default-Stop:      1
 # Short-Description: Dklab Realplexor Comet Server.
@@ -18,14 +18,14 @@
 ### END INIT INFO
 
 #
-# If you store dklab_realplexor in a different location, 
+# If you store dklab_realplexor in a different location,
 # it is recommended not to change CWD, but run:
 #
 # ln -s /path/to/your/dklab_realplexor /opt/dklab_realplexor
 #
 # If you want to change some variables, it is recommended
 # to put these changes to /etc/default/YOUR_INIT_SCRIPT_NAME
-# (typically /etc/default/dklab_realplexor). All variables 
+# (typically /etc/default/dklab_realplexor). All variables
 # defined there will override current script.
 #
 CWD="/opt/dklab_realplexor"
@@ -51,79 +51,79 @@ fi
 
 # Script to execute.
 if [ -x $CWD/dklab_realplexor ]; then
-	BIN="$CWD/dklab_realplexor"
+    BIN="$CWD/dklab_realplexor"
 else
-	BIN="/usr/bin/perl $CWD/dklab_realplexor.pl"
+    BIN="/usr/bin/perl $CWD/dklab_realplexor.pl"
 fi
 
 
 start () {
-	export CONF
-	for CONF in $ADDCONFIG; do
-		PIDFILE=${PIDPREFIX}_`basename $CONF`.pid
-		PID=`cat $PIDFILE 2>/dev/null`
-		if [ "$PID" != "" ] && kill -s 0 $PID 2>/dev/null; then
-			echo "dklab_realplexor for $CONF is already running"
-		else
-			rm -f $PIDFILE 2>/dev/null
-			cd $CWD && $BIN $CONF -p $PIDFILE 2>&1 | logger -p `eval "echo $LOGPRI"` -t `eval "echo $LOGTAG"` &
-			sleep 1
-			PID=`cat $PIDFILE 2>/dev/null`
-			if [ "$PID" != "" ]; then
-				echo "OK: $CONF"
-			else
-				echo "FAILED: $CONF; see logs"
-			fi
-		fi
-	done
+    export CONF
+    for CONF in $ADDCONFIG; do
+        PIDFILE=${PIDPREFIX}_`basename $CONF`.pid
+        PID=`cat $PIDFILE 2>/dev/null`
+        if [ "$PID" != "" ] && kill -s 0 $PID 2>/dev/null; then
+            echo "dklab_realplexor for $CONF is already running"
+        else
+            rm -f $PIDFILE 2>/dev/null
+            cd $CWD && $BIN $CONF -p $PIDFILE 2>&1 | logger -p `eval "echo $LOGPRI"` -t `eval "echo $LOGTAG"` &
+            sleep 1
+            PID=`cat $PIDFILE 2>/dev/null`
+            if [ "$PID" != "" ]; then
+                echo "OK: $CONF"
+            else
+                echo "FAILED: $CONF; see logs"
+            fi
+        fi
+    done
 }
 
 stop () {
-	for CONF in $ADDCONFIG; do
-		PIDFILE=${PIDPREFIX}_`basename $CONF`.pid
-		PID=`cat $PIDFILE 2>/dev/null`
-		if [ "$PID" == "" ]; then
-			echo "dklab_realplexor for $CONF is not running (pid file is empty)"
-		else
-			kill $PID
-			echo "OK: $CONF"
-		fi
-	done
+    for CONF in $ADDCONFIG; do
+        PIDFILE=${PIDPREFIX}_`basename $CONF`.pid
+        PID=`cat $PIDFILE 2>/dev/null`
+        if [ "$PID" == "" ]; then
+            echo "dklab_realplexor for $CONF is not running (pid file is empty)"
+        else
+            kill $PID
+            echo "OK: $CONF"
+        fi
+    done
 }
 
 reload () {
-	for CONF in $ADDCONFIG; do
-		PIDFILE=${PIDPREFIX}_`basename $CONF`.pid
-		PID=`cat $PIDFILE 2>/dev/null`
-		if [ "$PID" == "" ]; then
-			echo "dklab_realplexor for $CONF is not running (pid file is empty)"
-			start
-		else
-			# Send SIGHUP to process group.
-			kill -s 1 $PID
-			echo "OK: $CONF"
-		fi
-	done
+    for CONF in $ADDCONFIG; do
+        PIDFILE=${PIDPREFIX}_`basename $CONF`.pid
+        PID=`cat $PIDFILE 2>/dev/null`
+        if [ "$PID" == "" ]; then
+            echo "dklab_realplexor for $CONF is not running (pid file is empty)"
+            start
+        else
+            # Send SIGHUP to process group.
+            kill -s 1 $PID
+            echo "OK: $CONF"
+        fi
+    done
 }
 
 case $1 in
-	start)
-		start
-	;;
-	stop)
-		stop
-	;;
-	restart)
-		stop
-		sleep 2
-		start
-	;;
-	reload)
-		reload
-	;;
-	*)
-		echo "Usage:"
-		echo "  $0 {start|stop|restart|reload}"
-		exit 1
-	;;
+    start)
+        start
+    ;;
+    stop)
+        stop
+    ;;
+    restart)
+        stop
+        sleep 2
+        start
+    ;;
+    reload)
+        reload
+    ;;
+    *)
+        echo "Usage:"
+        echo "  $0 {start|stop|restart|reload}"
+        exit 1
+    ;;
 esac
